# Generated by Django 2.2.7 on 2020-05-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200522_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
