# Generated by Django 2.2.7 on 2020-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_5',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_6',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
