# Generated by Django 2.2.7 on 2020-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200522_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='CA', max_length=120, null=True),
        ),
    ]
